[package]
name = "giz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.28.0"
glow = "0.11.2"
serde = { version = "1.0", features = ["derive"] }
bevy_ecs = "0.8.0"
deno_core = "0.138.0"
cgmath = "0.18.0"
bytemuck = { version = "1.11.0", features = ["derive"] }
log = "0.4.17"
uuid = "1.1.2"
fern = { version = "0.6.1", features = ["colored"] }
chrono = "0.4.20"
