[workspace]
resolver = "2"
members = [
  "crates/giz_core",
  "crates/giz_bin",
  "crates/giz_render",
  "crates/giz_scripting",
  "crates/giz_input",
  "crates/giz_loader",
  "crates/giz_scripting/macros",
  "crates/giz_math",
  "crates/giz_build"
]
